#!/bin/bash

WEEK=$(date "+%-V")

if [ "$WEEK" -eq 1 -o "$WEEK" -eq 14 -o "$WEEK" -eq 22  -o "$WEEK" -eq 33 ]; then
	echo "OTV"
elif [ "$WEEK" -ge 3 -a "$WEEK" -le 10 ]; then
	echo "LV$(( "$WEEK" - 2 ))"
elif [ "$WEEK" -ge 12 -a "$WEEK" -le 13 ]; then
	echo "LV$(( "$WEEK" - 11 ))"
elif [ "$WEEK" -ge 15 -a "$WEEK" -le 20 ]; then
	echo "LV$(( "$WEEK" - 12 ))"
elif [ "$WEEK" -ge 35 -a "$WEEK" -le 42 ]; then
	echo "LV$(( "$WEEK" - 34 ))"
elif [ "$WEEK" -ge 44 -a "$WEEK" -le 51 ]; then
	echo "LV$(( "$WEEK" - 43 ))"
elif [ "$WEEK" -eq 11 -o "$WEEK" -eq 21 -o "$WEEK" -eq 43 -o "$WEEK" -eq 2 ]; then
	echo "TV"
else
	echo "V$WEEK"
fi
