#!/bin/bash

# Variables
DATE="" # Default to empty

# Get command line arguments
while getopts 'd:h' flag; do
	case "${flag}" in
		# Make a string with "-d" and our date.
		# This is later used when calling date.
		d) DATE="-d ${OPTARG}" ;;

		# Help text
		h)  echo "Usage: $0 [OPTION]"
			echo "Get the week in the academic year"
			echo ""
			echo "  -d DATE    Get the week for DATE. Default is today."
			echo "             Works like date's -d flag."
			echo "  -h         Display this help message."
			exit 0
			;;

		# Just exit on unexpected options.
		# getopts prints a nice error message.
		*) exit 1 ;;
	esac
done

# Get the current week if DATE is empty, otherwise get the specified week.
# Redirect errors to /dev/null, and handle error output ourselves.
if [[ -z $DATE ]]; then
    if ! WEEK=$(date "+%-V" 2> /dev/null); then
        echo "$0: Something went wrong with date"
        exit 1
    fi
else
    if ! WEEK=$(date "$DATE" "+%-V" 2> /dev/null); then
        echo "$0: invalid date '${DATE:3}'"
        exit 1
    fi
fi


# Horrible wall of ifs.
# First checks if our week is a reexamination week, checks if it's an
# examination week, checks if it's a teaching week, and calculates which one it
# is with an offset, and finally just outputs the week's number if it doesn't
# fall in any of the above categories. Study period 4 is in there twice because
# it has a reexamination week in the middle.
if (( WEEK == 1 || WEEK == 14 || WEEK == 22  || WEEK == 33 )); then
    # Reexamination week.
	echo "OTV"
elif (( WEEK == 11 || WEEK == 21 || WEEK == 43 || WEEK == 2 )); then
    # Examination week.
	echo "TV"
elif (( WEEK >= 35 && WEEK <= 42 )); then
    # Study period 1
	echo "LV$(( WEEK - 34 ))"
elif (( WEEK >= 44 && WEEK <= 51 )); then
    # Study period 2
	echo "LV$(( WEEK - 43 ))"
elif (( WEEK >= 3 && WEEK <= 10 )); then
    # Study period 3
	echo "LV$(( WEEK - 2 ))"
elif (( WEEK >= 12 && WEEK <= 13 )); then
    # Study period 4
	echo "LV$(( WEEK - 11 ))"
elif (( WEEK >= 15 && WEEK <= 20 )); then
    # Study period 4
	echo "LV$(( WEEK - 12 ))"
else
    # Week not in the academic year.
	echo "V$WEEK"
fi

exit
